### ISSUE TITLE
Report Kotlin csiki-csuki

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/renovate-config#11]

**Comment by TWiStErRob** [comment]
Example with Mockito-kotlin:
https://github.com/TWiStErRob/net.twisterrob.colorfilters/pull/183
https://github.com/TWiStErRob/net.twisterrob.colorfilters/pull/184

**Comment by TWiStErRob** [comment]
Might be the same root cause as #18

**Comment by TWiStErRob** [comment]
Testing https://github.com/TWiStErRob/renovate-ever-changing-test

**Comment by TWiStErRob** [comment]
Doesn't seem to reproduce with Mockito-kotlin. Minimal repro I tried:
`gradle/libs.versions.toml`
```toml
[versions]
mockito = "5.7.0"
mockito-kotlin = "4.1.0"

[libraries]
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
```
```json
{
	"$schema": "https://docs.renovatebot.com/renovate-schema.json",
	"extends": [
		":dependencyDashboard",
		":disableRateLimiting",
		"group:mockitoMonorepo"
	],
	"commitMessageExtra": "from {{{currentValue}}} to {{{newValue}}}{{#if isMajor}} (major v{{{newMajor}}}){{else}}{{/if}}",
	"separateMajorMinor": true,
	"separateMultipleMajor": true,
	"separateMinorPatch": true,
	"packageRules": [
		{
			"groupName": "mockito monorepo",
			"description": "Add nhaarman dependency to builtin 'mockito monorepo' group defined at https://docs.renovatebot.com/presets-group/#groupmockitomonorepo.",
			"matchPackageNames": [
				"com.nhaarman.mockitokotlin2:mockito-kotlin",
				"com.nhaarman:mockito-kotlin"
			]
		}
	]
}
```
